/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simplest.possible.implementation;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class PrimeFactors {

    public <Integer> List<Integer> of(int number) {
        List<java.lang.Integer> result ;
        if (number == 1)
            return Collections.emptyList();
        result = new ArrayList<>(number);
        result.add(2);
        return (List<Integer>) result;
    }
}
